# Generated by Django 5.0.6 on 2024-08-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('black', 'Black'), ('white', 'White')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(blank=True, choices=[('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('lg', 'Lg'), ('xxl', 'XXL')], max_length=100, null=True),
        ),
    ]
